apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebc-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-098a861d7078e453b