apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-roboshop"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-efs-dynamic
  labels:
    purpose: efs-dynamic-demo
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: efs-dynamic-demo
      project: roboshop
  template:
    metadata:
      labels:
        purpose: efs-dynamic-demo
        project: roboshop
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts"
            - name: persistent-storage
              mountPath: /usr/share/nginx/html
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic
  labels:
    purpose: efs-dynamic-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port