apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
  labels:
    purpose: config
    environment: dev
data:
  MYSQL_HOST: "mysql.roboshop.svc.cluster.local"
  MYSQL_PORT: "3306"
  MYSQL_PASSWORD: "admin@123"
