apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    purpose: deployment-scale
    environment: dev
    app: nginx
    project: roboshop
spec:
  replicas: 8
  selector:
    matchLabels:
      purpose: deployment-scale
      environment: dev
      app: nginx
      project: roboshop
  template:
    metadata:
      labels:
        purpose: deployment-scale
        environment: dev
        app: nginx
        project: roboshop

    spec:
      containers:
        - name: nginx
          image: nginx
