apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: roboshop
    component: mysql
    tier: database
    environment: dev
spec:
  containers:
   - name: nginx
     image: nginx
     