apiVersion: v1
kind: Pod
metadata:
  name: multi0caontainer
  labels:
    project: roboshop
    purpose: demo
spec:
  containers:
   - name: nginx
     image: nginx
   - name: almalinux
     image: almalinux:9
      