apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx

  - name: almalinux
    image: almalinux
    command: [ "sleep", "3600" ]
    