apiVersion: v1
kind: Pod
metadata:
  name: env-pod-config
  labels:
    project: roboshop
    component: nginx
    tier: frontend
    environment: dev
spec:
  containers:
   - name: nginx
     image: nginx
     envFrom:
      - configMapRef:
          name: pod-config
          