apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
  - name: app
    image: nginx
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
      requests:
        memory: "32Mi"
        cpu: "100m"
        