apiVersion: v1
kind: Secret
metadata:
  name: my-secret 
  labels:
    purpose: secret-demo
    env: dev
type: Opaque
data:
  MYSQL_HOST: "YWRtaW4="
  MYSQL_PASSWORD: "YWRtaW4zMjE="  # base64 encoded value for "password"

