apiVersion: v1
kind: Secret
metadata:
  name: my-secret 
  labels:
    purpose: secret-demo
    env: dev
type: Opaque
data:
MYSQL_HOST= "Robshop-Secret-Host"
MYSQL_PORT= "3306"
MYSQL_PASSWORD= "cGFzc3dvcmQ="  # base64 encoded value for "password"

