apiVersion: v1
kind: Service
metadata:
  name: my-service-np
  labels:
    purpose: service-demo
    project: roboshop
    environment: dev
spec:
  selector:
    purpose: service-demo
    project: roboshop
    environment: dev
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

apiVersion: v1
kind: Pod
metadata:
  name: my-pod-np
  labels:
    purpose: service-demo
    project: roboshop
    environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
  