apiVersion: v1
kind: Service
metadata:
  name: service-lb
spec:
  type: LoadBalancer
  selector:
    purpose: service-demo
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    purpose: service-demo
    project: roboshop
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: service-demo
      project: roboshop
      environment: dev
  template:
    metadata:
      labels:
        purpose: service-demo
        project: roboshop
        environment: dev
    spec:
      containers:
        - name: nginx
          image: nginx
