apiVersion: v1
kind: Service
metadata:
  name: my-service-np
  labels:
    purpose: service-demo
    project: roboshop
    environment: prod
spec:
  type: NodePort
  selector:
    purpose: service-demo-NodePort
    project: roboshop
    environment: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


  